eureka:
  client:
    serviceUrl:
      # 根据实际的注册发现地址添加，如果存在多个，使用逗号隔开/eureka/
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huangjianven/springclouddemo.git
# 访问git仓库的用户密码 如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
# 配置文件命名：{application}-{profile}.yml      gateway-prod.yml  application.yml
# 配置文件命名：/{label}/{application}-{profile}.yml   http://localhost:6666/gateway-prod.yml  http://localhost:6666/application-default.yml
#          username: *****
#          password: *****
#          basedir: /Users/admin/code/myProjects/java/imooc/SpringCloud_Sell/config/basedir
          search-paths: config-repo
server:
  port: 6666