server:
  port: 9999
eureka:
  client:
    enabled: false
    serviceUrl:
      # 根据实际的注册发现地址添加，如果存在多个，使用逗号隔开/eureka/
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    # 注册时的服务ID
    name: travelBusiness
  redis:
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    host: cfwpt.ybsjyyn.com
    port: 6379
    password: Larry*redis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.89.22.119:3306/travel_business?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Larry@mysql
mybatis-plus:
  mapper-locations: classpath*:com/example/entity/business/**/*.xml
logging:
  level:
    com: debug
    io.swagger.models.parameters.AbstractSerializableParameter: error